### ISSUE TITLE
Tracking Issue: Typescript policies

### ISSUE THREAD

**Issue by MarinPostma** [chiselstrike/chiselstrike#1790]
# Tracking Issue: Typescript Policies

This issue tracks the development of the Typescript policies feature. It serves as temporary documentation for the feature, as well as a platform for discussion for it.

## Documentation

Typescript policies allow the user to define policies at the type level for every entity, in plain typescript.

For each type, 7 policies can be defined.
- 4 filters
    - `read`
    - `create`
    - `update`
    - `delete`
- 2 transforms
    - `onRead`
    - `onWrite`
- `geoLocation`

All these policies are discussed in detail in the subsequent sections.

### Defining policies

Policies are defined in the `policies` folder of the ChiselStrike project. They are typescript files with the same name as the policy they are linked to. E.g, the `Person` entity will have its associated policies defined in the `policies/Person.ts`.

The policy file for an entity has an object default export that associates a policy name (as defined above), to the policy function.

In the following sections, we'll see how each policy is defined, and how they interact.

### Fitlers

There are 4 different filters, mirroring the CRUD operations. They are `read`, `create`, `update` and `delete`.

Filters are defined as follows:

```typescript
// in models/MyEntity.ts
export default {
    read: (e: MyEntity, ctx: ReqContext): Action => {
        if (request.method == "GET") {
                return Action.Skip
            }
        // filter code here
    },
    // other filters
}
```

The `ReqContext` contains information about the request, and has the following fields:
- `path: string`: the path of the request from which the entity is being accessed
- `method: string`: the method of the request
- `userId: string | undefined`: the id of the logged-in user
- `headers: Record<string, string>`: the headers of the request

`Action` tells the policy what should be done with the considered entity. It can be one of
- `Action.Allow`: Allow the endpoint to perform the action.
- `Action.Deny`: When performing an action on the considered entity, an exception is thrown. If not caught, an http response with the `403` code is returned.
- `Action.Skip`: If the policy is read, then all is as if the entity for which `Action.Skip` is returned did not exist in the request context. On any other filter, this is equivalent to a `Deny`.
- `Action.Log`: The entity is logged, and then `Allow`ed.

Any branch not covered by an explicit return statement will result in an `Action.Deny`.

Filters works in a similar fashion to UNIX permissions, that is, if one is not allowed to read an entity, then he is not allowed to write to it either.

#### Limitations
Not any code is allowed in filter policies. The outcome of a policy must be fully determinable from the function's input and terminate quickly. Currently, very little typescript is allowed in the filter policies, that is if-else conditions, that contain arbitrary logical expressions, and return statements, returning an `Action`.

These restrictions will be eased as we implement better code analysis.

### Transforms

Transforms allow arbitrary transformation to be applied to instances of entities. There are two transform policies:

- `onRead`: this transform is applied immediately after the `read` filter policy.
- `onWrite`: this transform is applied right after the `update` or `create` filter policy.

The transforms are defined as follows:

```typescript
// in models/MyEntity.ts
export default {
    onRead: (e: MyEntity, ctx: ReqContext): MyEntity => {
        if (e.someProp == someValue) {
            e.someOtherProp = undefined;
        }

        return e;
    },
}
```

#### limitations:
Transforms are more permissive than filters. They allow any arbitrary code, as long as it can be proven that it terminates, and does not have side effects. For now, the content on the transform function is run in a sandbox, and cannot access anything outside of it.

### Geolocation
The geolocation policy defines in which data center an entity will be saved.
```typescript
// in models/MyEntity.ts
export default {
    onRead: (e: MyEntity, ctx: ReqContext): string => {
        if (e.country == "france") {
            return "london";
        }

        return "us-east-1";
    },
}
```

#### Limitations
Limitations are the same as for transforms.

## Unresolved question
Questions open for discussion. Issues should be opened to discuss them, and then linked here.

### Product
- How should skip be handled in policies other than read
- Where should policies be defined (if not each in their own file)
- What should the defaults be for each policies, work ergonomics.

## TODO:
Things that yet need to be done, in no specific order:
- [ ] Better error handling (especially with parsing).
- [ ] Disallow changing id in transform.
- [ ] Allow variable definition and use in filters
- [ ] Expose helper functions to the policies
- [ ] Delete filter
- [ ] Extend policies to Kafka
- [ ] Perform analysis on transform functions to make sure they terminate.
- [ ] **Write tests**
- [ ] Support policies on nested entities
- [ ] Support property indexing (for request context headers)
- [ ] Expose feature flag to cli and chiseld
- [ ] Support `function` declaration for policies along with arrow functions.

### Unpredictable deny behavior

Consider the following endpoint:

```typescript
export default async function (req) {
    let person = await Person
        .cursor()
        .filter(x => x.age > 18 && someFunc())
        .toArray();
}
```

and the following policy:

```typescript
export default {
    read: (person, _) => {
        if (person.age < 18) {
            return Action.Deny;
        }

        return Action.Allow.
    }
}
```

Here it is easy to see that depending on whether chiselc is able or to optimize the `filter`, a call to the endpoint would either work correctly or throw an exception for the same entity set.
